version: '3.4'

services:
  testingsystemservice:
    image: ${DOCKER_REGISTRY-}testingsystemservice
    restart: always
    build:
      context: .
      dockerfile: TestingSystemService\Dockerfile
    volumes:
      - c:\config:c:\config:ro


  compilerservicesorchestrator:
    image: ${DOCKER_REGISTRY-}compilerservicesorchestrator
    restart: always
    build:
      context: .
      dockerfile: CompilerServicesOrchestrator\Dockerfile
    ports:
      - "1338:80"
    volumes:
      - c:\config:c:\config:ro
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine


  reflectiontesterservice:
    image: ${DOCKER_REGISTRY-}reflectiontesterservice
    restart: always
    build:
      context: .
      dockerfile: ReflectionTesterService\Dockerfile
    ports:
      - "1339:80"
    volumes:
      - c:\config:c:\config:ro


  functionaltestingservicesorchestrator:
    image: ${DOCKER_REGISTRY-}functionaltestingservicesorchestrator
    restart: always
    build:
      context: .
      dockerfile: FunctionalTestingServicesOrchestrator\Dockerfile
    ports:
      - "1340:80"
    volumes:
      - c:\config:c:\config:ro
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine

  codestyletesterservice:
    image: ${DOCKER_REGISTRY-}codestyletesterservice
    restart: always
    build:
      context: .
      dockerfile: CodeStyleTesterService\Dockerfile
    ports:
      - "1342:80"
    volumes:
      - c:\config:c:\config:ro

  hse.contest:
    image: ${DOCKER_REGISTRY-}hsecontest
    restart: always
    build:
      context: .
      dockerfile: HSE.Contest\Dockerfile
    ports:
      - "8888:80"
    volumes:
      - c:\config:c:\config:ro
